title: Dario Cavada
description: Personal Web Site
author: John Smith
logo: /static/img/avatar.png
github: https://github.com/dariocavada
about: Freelance developer and musician

baseurl: "http://dariocavada.github.com"
url: "http://dariocavada.github.com"

disqus_shortname: dariocavada
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
